### PR TITLE
Update the interactive heatmaps

### PR DESCRIPTION
**Pull request by jasminezhuoy**
Update the interactive heatmaps

### CODE REVIEW

**Comment by michaelweylandt** [comment]
Actually - one thing: can you rebase this PR so that e869e85 isn't in the commit history? This should be a pretty straight-forward commit history, so I'm not sure how that got in there. 

If you've never done a git rebase before, https://git-scm.com/book/en/v2/Git-Branching-Rebasing provides a good intro.

**Comment by jasminezhuoy** [comment]
> Looks good now that the timing problem is fixed. Anything else you want to do on this PR or should I go ahead and merge?

I saw there are some errors and notes regarding `test_cbass_sparsity_pattern`. Maybe we need to fix that.

**Comment by michaelweylandt** [comment]
The `std::bad_alloc` thing? If you have a windows machine and can reproduce it, that'd be great, but it's not new to this PR. It's been happening for a while - I think it's just a "too big a data set" thing in a test, but I'm not sure why we'd get it for only the new version of R.

**Comment by michaelweylandt** [comment]
Looks like the flaky windows R-devel test passed as well!

I'll merge this now.

**Pull request merged**
