### PR TITLE
Increase the number of frames in plots to 100

### PR DESCRIPTION
**Pull request by jasminezhuoy**
Solve #80 
Update #98

### CODE REVIEW

**Comment by michaelweylandt** [comment]
Hi @jasminezhuoy, 

As mentioned in #98, this needs to be targeted to `develop` not master. 

Do you think the message demoed in #104 would clarify this requirement?

**Comment by jasminezhuoy** [comment]
> Hi @jasminezhuoy,
> 
> As mentioned in #98, this needs to be targeted to `develop` not master.
> 
> Do you think the message demoed in #104 would clarify this requirement?

The requirement is good. I forgot changing the branch and fixed it just now. Sorry for that.

**Comment by michaelweylandt** [comment]
This looks good to me. Are there any other places you think we should increase the frame rate?

**Comment by jasminezhuoy** [comment]
> This looks good to me. Are there any other places you think we should increase the frame rate?

Thanks for your help! I haven't noticed other places that needed to increase the frame rate.

**Pull request merged**
