### PR TITLE
Remove RNG from RCPP export

### PR DESCRIPTION
**Pull request by dansenglund**
https://github.com/DataSlingers/clustRviz/issues/94

### CODE REVIEW

**Comment by michaelweylandt** [comment]
Thanks @dansenglund 

Two changes before this is ready to merge: 

1) Can you change the target branch to `develop` instead of `master`? There should have been a message from a bot asking this automatically (see #104) but it didn't seem to happen for some reason.

2) Can you take the changes to `RcppExports.cpp` (the autogenerated file) out? 

Context: I develop on `develop` and use CI to automatically re-create the autogenerated stuff and webpage docs on `master` when a new commit is made (assuming it passes CI checks). This gives a cleaner commit history - no changes to generated files cluttering up `develop` - while still maintaining a stable directly usable version on `master` for users. A few weeks ago I moved the system from TravisCI to GitHub Actions, but it's still a bit buggy, hence the lack of bot notification. 

Thanks!

**Comment by michaelweylandt** [comment]
I looked into the lack of warning bot (first point above) - the relevant check code never got pushed to `master`, where it needs to be to check PRs to `master,` because of a weird segfault that prevented PR #104 from ever getting deployed.[1] I'm working on isolating the cause of that segfault now in WIP PR #108, which will hopefully revive the CI pipeline. 


[1] https://github.com/DataSlingers/clustRviz/runs/665750585?check_suite_focus=true

**Comment by dansenglund** [comment]
Realizing that I originally forked master, so it has one of your build commits in it now. I don't know an elegant way to work around this. Any advice?

**Comment by michaelweylandt** [comment]
Easiest way:  just make a new branch off `develop` and update the PR accordingly. (I can't remember if GH allows you to change the source of a PR or if you'd need a new one)

Slightly harder, but good git-fu to learn, you can re-base the branch off `develop` rather than `master.` https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by dansenglund** [comment]
Did some painful git magic, but things should finally be cleaned up

**Comment by michaelweylandt** [comment]
CI failure here is a weird, but unrelated, segfault in GIF rendering, so I'm going to merge anyways.

**Comment by michaelweylandt** [comment]
Closes #94

**Pull request merged**
