### PR TITLE
replaced aes_string with aes

### PR DESCRIPTION
**Pull request by kenzeng24**

### CODE REVIEW

**Comment by michaelweylandt** [comment]
Looks good! Do you want to close the other PRs attempting this?

If CI is happy (enough) with it, I'll go ahead and merge

**Comment by michaelweylandt** [comment]
Two CI failures: 
- Windows failure is a very small numerical tolerance issue, unrelated to this PR
- MacOS failure is due to lack of CRAN provided binaries for R-devel. 

Both of these are harmless, so I'm happy to merge. 

@kenzeng24 Anything else you want to do in this PR or is it good to go?

**Comment by michaelweylandt** [comment]
Hey @kenzeng24  - just a quick ping on this. 

Anything else you think needs to be merged or is it good to go? (I can't think of anything else)

**Comment by kenzeng24** [comment]
I think it should be good.

**Pull request merged**
