### PR TITLE
[Review Requested] Update Accessors

### PR DESCRIPTION
**Pull request by michaelweylandt**
I'm working on a new set of "accessors" for `CARP` and `CBASS` objects. The design splits
out the current `clustering` function into three parts: 

- `get_cluster_labels`: to get a factor vector of labels
- `get_cluster_centroids`: to get a k-by-p matrix of centroids (not defined for `CBASS`)
- `get_clustered_data`: to get a n-by-p matrix of the clustered values

Thoughts on the design? See the tests for the `CARP` accessors for examples. (I'm not done with `CBASS` yet.)

I'm doing a lot more computational work on the `CBASS` side, including the PC projection which we had previously been omitting, so it's slower for now. I'll keep working on performance as I go. This is with an eye towards allowing `CARP`-path style visualizations for `CBASS` objects as well (#25)

### CODE REVIEW

**Comment by michaelweylandt** [comment]
@jjn13 Can you take a look at this design? 

It has a few advantages over the current `clustering` function: 

1) It always returns in the original data space, regardless of preprocessing used
2) It is type-stable in the sense of it always returns a factor vector or matrix (as appropriate) of predictable size, never a list
3) There is a single function for each piece of information rather than a "super function" 

If this looks good, I'll update the tests of the current `clustering` function to use this interface and move `clustering` internal. (We can't drop it entirely because it appears to be used by some of the plotting code. We also only return the "refitted" solution for now, so we can't use
this as the building-block for the interactive path plots)

This design also adds PC projection to `CBASS` results, which will eventually allow us to have `CBASS` path plots (#25)

**Comment by jjn13** [comment]
I think these are all good changes. I especially like breaking out the clustering function.

Also returning on the original scale is probably preferable.

**Comment by michaelweylandt** [comment]
Thanks -- I'll finish it up and then send it to you for formal review.

**Comment by michaelweylandt** [comment]
I appreciate the vote of confidence, but the work isn't done yet :-)

Do you have any thoughts on defining `get_cluster_centroids` for bi-clustering. The idea of "cluster centroids" makes sense, but I'm not sure how to set up the return object.

**Comment by jjn13** [comment]
I think both changes are fine. I don't think the clustering.CARP change should affect anything. I think calculating CBASS var/obs clusterings separately is fine. The only place where it might matter is in the dynamic visualization (which is controlled by lambda/percent regularization). I'll check this as I incorporate gganimate.

**Comment by michaelweylandt** [comment]
Molto grazie - I'll pull the trigger and merge it.

**Pull request merged**
