### PR TITLE
Fix Transpose in clustering.CBASS

### PR DESCRIPTION
**Pull request by jjn13**
Changed code to make clustering mean matrix returned by clustering.CBASS have same dimensions as input. Also added a basic test related to this, and (hopefully?) made row/column/variable/observation-related names more readable.

### CODE REVIEW

**Comment by jjn13** [comment]
Gotcha. Vignette error was indexing issue after fixing the transpose; it was trying to display 5 variables (the simple vignette example less than this) instead of 5 observations.

Added tests for "extremes" (full and 0 regularization); I think this should also address the other cbass clustering related bug report.

Also added test for observation/variable label consistency in the resulting cluster mean matrix.

**Comment by jjn13** [comment]
No please feel free

**Comment by michaelweylandt** [comment]
Done -- I'll approve it, but can you take a look over it as well and make sure it looks ok.

**Comment by jjn13** [comment]
Gave it another look over. Looks good and am going to merge.

**Comment by michaelweylandt** [comment]
Thanks!

Two minor things: 

1) When you merge a PR through GitHub, could you use a more informative commit message than GH's default? I usually try to write a summary of what the PR does (at a high level), leaving the details to the individual commit messages. 

2) When a PR closes a issue, you can add that to the message and automatically close the issue (thereby linking the two long-term, which is useful for code archaeology).

**Pull request merged**
