### PR TITLE
Increase the number of frame in plots from 21 to 100

### PR DESCRIPTION
**Pull request by jasminezhuoy**
Solve issue #80

### CODE REVIEW

**Comment by michaelweylandt** [comment]
Does it make sense to make a similar change here: https://github.com/DataSlingers/clustRviz/blob/7469817ca3bcb2306ab3744c2813ce6479e8086f/R/plot_cbass.R#L178 ?

**Comment by michaelweylandt** [comment]
Linking to #80 for completeness.

**Comment by michaelweylandt** [comment]
@jasminezhuoy A few days back, I had to temporarily disable a test because I was getting a weird "fps must be a factor of 100" message: https://github.com/DataSlingers/clustRviz/commit/c3321ec1546026a0e5ce05db0f865f1909f785c0  

Does this commit fix that issue? (*i.e.*, does that test run now with your change?)

**Comment by michaelweylandt** [comment]
@jasminezhuoy Can you change the "target branch" of this pull request to `develop`? I use `master` for autogenerated stuff, not mainline development. This will also trigger a CI build.

**Comment by michaelweylandt** [comment]
Might also need to change https://github.com/DataSlingers/clustRviz/blob/1761f77075cee3117e34ab6e24f1dae111a632f9/R/save.R#L44 for consistency

**Comment by jasminezhuoy** [comment]
@michaelweylandt I changed 'step' and 'by' in different functions and now they may all generate gif with 100 frames. Besides, I tested CARP gganimate with my change, the error "fps must be a factor of 100" is fixed, but I came across new error "The animation object does not specify a save_animation method".

**Comment by michaelweylandt** [comment]
Hi @jasminezhuoy, 

Ok - something went weird here. I'm not sure where the last commit (with my name on it) with the 85 changed files is coming from. Let me look into that tomorrow. 

Your first commit (changing the frame counts) looks good - what's going on with the second two? Was it trying to unskip the test - seeing it still fail - and putting the skip back in place? 

I'm not sure what `the animation object...` refers to. I've seen a similar message, but haven't been able to hunt it down.

**Comment by jasminezhuoy** [comment]
Hi @michaelweylandt ,

Yes as you guess, the second two commits are trying to figure out whether the error "fps must be a factor of 100" is fixed. Since this error has disappeared, but new error occurred, do I need to upskip this test?

**Comment by michaelweylandt** [comment]
Can you reproduce the error on your own computer? If so, it might be useful to set up a quick Zoom call to pair-program and hunt down the source.

**Comment by jasminezhuoy** [comment]
> Can you reproduce the error on your own computer? If so, it might be useful to set up a quick Zoom call to pair-program and hunt down the source.

Hi @michaelweylandt , I tried to reproduce the error, but I didn't meet with it on my own laptop. Maybe for the reason that I use Macbook while the error occurred on Windows and Linux system.

**Comment by michaelweylandt** [comment]
Ok then. Let's not worry about it for now and leave it as an important TODO item for later.

**Comment by michaelweylandt** [comment]
Closed in lieu of #107

**Pull request closed without merging**
